name = "oherr"
description = "A Rust-style Result type for Ada (oh, error!)."
version = "0.1.0-dev"

authors = ["0xA672"]
maintainers = ["0xA672 <Cero0xA672@outlook.com>"]
licenses = "MIT OR Apache-2.0"
website = ""
tags = ["result", "error-handling", "functional", "rust", "option"]
github-login = '0xA672'
